### ISSUE TITLE
Upload Date?

### ISSUE THREAD

**Issue by timelady-victorious** [TheBlockBox/CMW#1]
The mod page says "hence the upload date", but the upload date is just 3/4/2021. What's special about that?

**Comment by RedstoneTim** [comment]
Well, the mod was supposed to be published on April 1st as a joke, except that the coding took a bit longer than anticipated due to some issues. Add the time required for approval onto that and you get the actual upload date.

**Comment by timelady-victorious** [comment]
Ah, i figured it might be that. Very sad you missed it.
